/////////////////////////////////////////////PRINCIPAL
import "./src/components/layout.css"
/////////////////////////////////////////////SECUNDARIOS-COMPONENTES
import "./src/components/header/header.css"
import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"
import "./src/components/slider/Slider.css"
import "./src/components/buttons/buttons.css"
import "./src/components/comp/comp.css"
import "./src/components/desplegable/desplegable.css"
import "./src/components/modals/modal.css"
import "./src/components/footer/footer.css"
import "./src/components/mapa/mapa.css"
import "./src/components/css-pages/accesibilidad.css"
import "./src/components/css-pages/avisolegal.css"
import "./src/components/css-pages/avisoprivacidad.css"
import "./src/components/css-pages/cookies.css"
import "./src/components/css-pages/crearqr.css"
import "./src/components/css-pages/sobrenosotros.css"